targets:
  cube:
    ids: [0]
    dict: "4x4_50"
    marker_size_m: 0.019

trailers:
  container:
    ids: [8]
    dict: "4x4_50"
    marker_size_m: 0.019
    far_ids: [1]
    far_dict: "4x4_50"
    far_marker_size_m: 0.10

